### ISSUE TITLE
Error on windows / discussing forwarding to groups

### ISSUE THREAD

**Issue by HellScre4m** [franciscod/telegram-universal-feed-bot#1]
Bad Request: Object expected as reply markup
Task exception was never retrieved
future: <Task finished coro=<api_call() done, defined at F:\Program Files (x86)\Python\Python35-32\lib\site-packages\aiotg\bot.py:56> exception=RuntimeError('Bad Request: Object expected as reply markup',)>
Traceback (most recent call last):
  File "F:\Program Files (x86)\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "F:\Program Files (x86)\Python\Python35-32\lib\site-packages\aiotg\bot.py", line 78, in api_call
    raise RuntimeError(err_msg)
RuntimeError: Bad Request: Object expected as reply markup

**Comment by franciscod** [comment]
Can repro on Linux. Thanks for reporting!

**Comment by franciscod** [comment]
Fixed here https://github.com/franciscod/telegram-universal-forwarder-bot/commit/73f6ec81468f25136a292671ccbe2507f07a1419! Please try it out (and remember to install the new versions of the deps)

**Comment by HellScre4m** [comment]
Thanks for quick response
It is fixed
However I was thinking this is kinda bot which can forward your messages to groups. Don't you know such bot scripts? (Seems it's kinda feed reader)
This issue can be marked as solved at last.

**Comment by franciscod** [comment]
This bot is currently more a "framework" for forwarding any general resource. The sample resource is a "clock", and you can subscribe to N-minute clocks. It would be nice to have a "forward private messages to group"! What's your use case?

**Comment by HellScre4m** [comment]
Well in fact my case is to forward a messages which is forwarded to the bot, to all the groups which bot is a member of. I want to broadcast my channel messages to multiple relevant group (e.g. fun groups). 
The point is, it should forward from that channel not to send a new message with the same content.
Is adding such feature possible? All I know that this feature is highly requested from many users and your bot can be highly popular by implementing it.
Thanks for caring :) I can suggest much more features, but this is my own personal use case
